package management.entity;
// Generated Dec 14, 2022, 9:49:56 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phieunhap generated by hbm2java
 */
@Entity
@Table(name = "phieunhap")
public class Phieunhap implements java.io.Serializable {

	private int mapn;
	
	private Nhacungcap nhacungcap;
	private Nhanvien nhanvien;
	private Date ngaynhap;
	private Set<Ctpn> ctpns = new HashSet<Ctpn>(0);

	public Phieunhap() {
	}

	public Phieunhap(int mapn,  Nhanvien nhanvien) {
		this.mapn = mapn;
		
		
		this.nhanvien = nhanvien;
	}
	

	public Phieunhap(int mapn, Nhanvien nhanvien, Date ngaynhap, Set<Ctpn> ctpns) {
		this.mapn = mapn;
	
		
		this.nhanvien = nhanvien;
		this.ngaynhap = ngaynhap;
		this.ctpns = ctpns;
	}

	@Id

	@Column(name = "MAPN", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public int getMapn() {
		return this.mapn;
	}

	public void setMapn(int mapn) {
		this.mapn = mapn;
	}

	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MANV", nullable = false)
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAYNHAP", length = 10)
	public Date getNgaynhap() {
		return this.ngaynhap;
	}

	public void setNgaynhap(Date ngaynhap) {
		this.ngaynhap = ngaynhap;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phieunhap")
	public Set<Ctpn> getCtpns() {
		return this.ctpns;
	}

	public void setCtpns(Set<Ctpn> ctpns) {
		this.ctpns = ctpns;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MANCC", nullable = false)
	public Nhacungcap getNhacungcap() {
		return this.nhacungcap;
	}

	public void setNhacungcap(Nhacungcap nhacungcap) {
		this.nhacungcap = nhacungcap;
	}

}
